### ISSUE TITLE
Sword Rendering

### ISSUE THREAD

**Issue by RangerNorth** [RiskyKen/Armourers-Workshop#216] opened 2018-01-18 04:33 UTC
I noticed when you make a sword in the game, if you want to have to classic vanilla style instead of the more voxel style the placement in hand is off. I made a staff and when you make it the pixeled way no matter which way you go its either to far by your players head or its sticking into the ground. It would be great if there was a way to make an option of Pixel or Voxel in the sword GUI settings that way depending on the style you prefer you can build to your liking, how hard would that be to add? Or would it be simple to rotate the position in hand and add a setting to enable it?

**Comment by RiskyKen** [comment] 2018-03-28 11:38
Duplicate of #89 .

**Closed by RiskyKen** 2018-03-28 11:38 UTC
Labels: duplicate
