### ISSUE TITLE
[BUG] Arrow is not the customize one

### ISSUE THREAD

**Issue by Syoicks** [RiskyKen/Armourers-Workshop#294] opened 2019-10-09 15:46 UTC
When i'm using a bow, the arrow isn't the customize one, it's the normal minecraft bow.
I tried to search if someone had the same bug but i think i'm the only one or i missed something
help...

**Comment by LordPhrozen** [comment] 2020-01-06 17:01
This is a known and incomplete feature, not a bug. Closing ticket, watch mod updates for this feature add.

**Closed by LordPhrozen** 2020-01-06 17:01 UTC
Labels: bug
