### ISSUE TITLE
skin bug

### ISSUE THREAD

**Issue by TheChronomancer** [RiskyKen/Armourers-Workshop#112] opened 2016-05-06 15:55 UTC
when i used the dev build posted on #110 my skin ended uplooking al pink and black
my mods list
![image](https://cloud.githubusercontent.com/assets/8211402/15078462/3845381e-1368-11e6-8929-cbe938d3bb96.png)

**Comment by RiskyKen** [comment] 2016-05-06 16:48
Are you getting any errors in the console?

**Comment by RiskyKen** [comment] 2016-05-06 18:37
Can you test without Et Futurum?

**Comment by RiskyKen** [comment] 2016-05-06 19:00
Try setting "Skin overlays" to false in the Et Futurum config.

**Comment by TheChronomancer** [comment] 2016-05-06 19:32
i just got rid of et futurum  and everything worked fine

**Comment by RiskyKen** [comment] 2016-05-06 19:34
Duplicate of https://github.com/RiskyKen/Armourers-Workshop/issues/107

**Closed by RiskyKen** 2016-05-06 19:34 UTC
Labels: bug, compatibility, duplicate, investigating
