### ISSUE TITLE
More Player Models 

### ISSUE THREAD

**Issue by MeifwaLeader** [RiskyKen/Armourers-Workshop#241] opened 2018-06-24 07:57 UTC
I'm trying to fix this bug and it's a bit hard to explain but the actions aren't working and neither are the scaling or custom feasters (hair, eyes, beards, skirts, ect) and I've tried the con something mod turning off and on and I've restarted my game countless times and it's only started since I've added models from blender into minecraft with blockbuster and metomorph but I hope it's not them cause I like them and yes if your asking I am using more then 1 mod

**Comment by LordPhrozen** [comment] 2018-06-27 16:00
Things that replace or change how the player model work defiantly cause issues. This is the same for animation modifications, and are incredibly difficult to support. I would not be surprised if this wasn't able to be addressed. More things like this however I'm sure are planned for newer reworks in the distant future.

**Comment by LordPhrozen** [comment] 2018-06-27 16:09
Also this is a duplicate of #213 , Suggest to close.

**Closed** 2018-06-27 17:03 UTC
