### ISSUE TITLE
Lighting Bug

### ISSUE THREAD

**Issue by Beadsmith2** [RiskyKen/Armourers-Workshop#139] opened 2016-10-07 18:21 UTC
Not sure if this is exclusively because i use Dynamic Lights, but even when I remove all mods besides this one:
When i break a block, sometimes it does not update the lighting for the surrounding blocks, and leaves an ultra dark shadow. This can be especially dangerous when it happens to multiple blocks in an area, because i cant see anything, and mobs could possibly spawn (has not happened to date though). Even with dynamic lights' torches, it will not update the lighting - i usually have to place another block and break that, and then _sometimes_ it will fix it. also annoying when cutting down trees.
That is the only bug i have found, and i have NO idea what causes it. But it's enough i cant use the mod. otherwise, this mod would probably be my #1 favorite mod ever, because of the total customization :)

Oh, actually one other thing: compatability with TConstructs. I can use both, but i cant reskin TConstructs weaponry for some reason. Thanks mate, keep up the good work, and i seriously love this mod!

-Beadsmith2

**Comment by RiskyKen** [comment] 2016-10-09 21:27
An issue like this has already been reported but I have been unable to reproduce it on my system.

https://github.com/RiskyKen/Armourers-Workshop/issues/123

Are you also using a texture pack???

**Comment by RiskyKen** [comment] 2017-08-22 08:39
Closed duplicate of https://github.com/RiskyKen/Armourers-Workshop/issues/123

**Closed by RiskyKen** 2017-08-22 08:39 UTC
Labels: need info
