### ISSUE TITLE
Bugged Green Blocks

### ISSUE THREAD

**Issue by GumSkyloard** [RiskyKen/Armourers-Workshop#100] opened 2016-03-09 19:11 UTC
Hey Risky! Your mod is amazing! I really like your mod! :D But there's a little bug on it.. When I put any of the equipment cubes, it ALL gets green- the cubes, i mean. They don't change, even when i paint them! But when i turn it into a item, it gets the colors it should have.. Well, that's it.. hope ya can fix it! :smiley: 

![2016-03-09_19 02 30](https://cloud.githubusercontent.com/assets/17749977/13647088/63aa9c44-e62a-11e5-88dd-bbee5348fd1c.png) The bugged blocks..
![2016-03-09_19 08 04](https://cloud.githubusercontent.com/assets/17749977/13647087/63aa67a6-e62a-11e5-849b-61790df4528e.png) Wait, they're not bugged anymore!
![2016-03-09_19 08 31](https://cloud.githubusercontent.com/assets/17749977/13647086/63a94510-e62a-11e5-9424-7aaef9c1c89d.png)
I'm not the best modeler.. :P

~Gum

**Comment by RiskyKen** [comment] 2016-03-10 14:06
Mod list please.

**Comment by RiskyKen** [comment] 2017-08-22 08:36
Closed duplicate of https://github.com/RiskyKen/Armourers-Workshop/issues/105

**Closed** 2017-09-20 13:22 UTC
Labels: duplicate, need info
