### ISSUE TITLE
Crash when using painter

### ISSUE THREAD

**Issue by duskshadowbrony** [RiskyKen/Armourers-Workshop#60] opened 2015-08-06 14:29 UTC
Moving a brush in or out crashes the server.

http://pastebin.com/MmUUtUNH

Worked fine last build, probably going to switch to that.

**Comment by RiskyKen** [comment] 2015-08-06 15:00
Duplicate of https://github.com/RiskyKen/Armourers-Workshop/issues/59

**Closed by RiskyKen** 2015-08-06 15:00 UTC
Labels: duplicate
