### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Gaahbiru** [RiskyKen/Armourers-Workshop#365] opened 2021-07-10 01:23 UTC
**sword skins do not appea**
I'm on version 1.12.2, and the sword skins don't appear on third person.
I tried looking for something in the configs, but I didn't find anything.

![image](https://user-images.githubusercontent.com/87214239/125147786-f36b9e80-e103-11eb-9d63-846cedcfea2d.png)
![image](https://user-images.githubusercontent.com/87214239/125147853-73920400-e104-11eb-9fea-288e2d7350b7.png)

**Comment by DoomRater** [comment] 2021-07-10 02:27
Please provide a mod list.  Specifically, is Obfuscate in your mod list?

**Comment by Gaahbiru** [comment] 2021-07-10 10:05
sheesh...I tried to remove the obfuscate and it worked. thx, I didn't know it was incompatible

**Comment by DoomRater** [comment] 2021-07-10 15:54
Closing as duplicate of #284 and #325.

**Closed by DoomRater** 2021-07-10 15:54 UTC
Labels: bug
