### ISSUE TITLE
crash when hovering skin

### ISSUE THREAD

**Issue by Zirker** [RiskyKen/Armourers-Workshop#228] opened 2018-03-30 23:07 UTC
on a server that I'm playing players are crashing while "making a custom sword skin and we wanted to save it. but we hover over it and it crashes us." - quote from one of them. I don't much about the mod is it a cross mod problem?

Crash report from one of the players:
https://pastebin.com/uka2LPdK

**Comment by RiskyKen** [comment] 2018-03-30 23:15
Duplicate of #226. Can you please test the latest dev version posted on discord and tell me if you still get the crash. https://discord.gg/SMjJj5R

**Comment by RiskyKen** [comment] 2018-03-30 23:18
Here is also a direct link https://cdn.discordapp.com/attachments/301410799044395008/429272436500987904/Armourers-Workshop-1.7.10-0.48.2-pre1.jar

**Comment by RiskyKen** [comment] 2018-04-10 16:37
Fix

**Closed by RiskyKen** 2018-04-10 16:37 UTC
Labels: duplicate
