### ISSUE TITLE
Can you remove a skin from an item

### ISSUE THREAD

**Issue by adamjis** [RiskyKen/Armourers-Workshop#238] opened 2018-06-10 21:31 UTC
So basicly i was creating a sword for the server i work on, i finished creating it and i bound the sword skin to an item and began working on another sword, i got told to save the original item to the library but when i was trying i realised it was attached to a diamond sword, is there a way to remove the sword skin from the sword

**Comment by LordPhrozen** [comment] 2018-06-19 13:27
Duplicate of #233

**Closed** 2018-06-19 13:34 UTC
Labels: duplicate
