### ISSUE TITLE
[Suggestion] Rotate block 180° for consistency

### ISSUE THREAD

**Issue by EzerArch** [RiskyKen/Armourers-Workshop#278] opened 2019-07-02 08:42 UTC
When I place a vanilla block, such as a furnace or dispenser, or a modded block, its front face faces towards me. But at the Armourer and on placement, the block has its front face facing on the opposite direction.

EDIT: Still on the Armourer, all the armour parts face North, except the block, which faces South.

**Comment by RiskyKen** [comment] 2019-07-08 08:58
Duplicate of #13. All Armourer parts face north.

**Closed by RiskyKen** 2019-07-08 08:58 UTC
Labels: duplicate
