### ISSUE TITLE
[Error] When wearing Armourers item

### ISSUE THREAD

**Issue by Chering031** [RiskyKen/Armourers-Workshop#152] opened 2017-01-13 07:53 UTC
Reinstall Minecraft and Workshop mode. But the same thing repeats.
Could you fix this bug?
mod version 0.42.5
[https://www.youtube.com/watch?v=wWnigf_FxjM](url)

**Comment by RiskyKen** [comment] 2017-01-13 11:07
Seen the video when I got up this morning.

If you don't have smart moving installed you set skinRenderType to 1 in the client configuration file. That should fix it.

Duplicate of #117

**Closed by RiskyKen** 2017-01-13 11:07 UTC
