### ISSUE TITLE
Compatibility with Naruto C 

### ISSUE THREAD

**Issue by MERENDA22** [RiskyKen/Armourers-Workshop#227] opened 2018-03-29 14:12 UTC
There are two main problems that i have noticed with these two mods; one being the armour staying in place, while the running animation from Jin's mod takes place, two being that Jin's skin which is slightly different than the normal Minecraft skin, is in conflict with the armour when you use the override function. If you could fix this at any time, i and presumably many other people would be very happy.

**Comment by RiskyKen** [comment] 2018-03-30 15:59
Duplicate of #211

**Closed by RiskyKen** 2018-03-30 15:59 UTC
Labels: duplicate
