### ISSUE TITLE
The Blocks keep changing Texture!

### ISSUE THREAD

**Issue by LuciferWPF** [RiskyKen/Armourers-Workshop#199] opened 2017-07-27 16:03 UTC
Hello, ive used this amazing mod many times, and today ive desided on a new server that I will make my own armour skin, but when I started placing the blocks down **_they went green and glowed_**, and the textures mixed I could tell what was on top or bottom and made it very hard to keep building, but when I asked if this is a problem the whole server has no one else had experienced it, I'm questioning maybe its because **I changed my settings** because of the server lag, or a problem that's caused from anything else? Please get back to me as soon as possible 

Screenshot 
![image](https://user-images.githubusercontent.com/30503981/28680197-8fd028c4-72ed-11e7-8577-52846018747a.png)

**Comment by RiskyKen** [comment] 2017-07-27 19:34
Do you have an AMD/ATI GPU?

**Comment by EzerArch** [comment] 2017-07-29 00:29
Interesting I sometimes get this kind of glitch too. Then I reset my Video Setup (Optifine), and it's back to normal.

**Comment by RiskyKen** [comment] 2017-08-22 08:35
Closed duplicate of https://github.com/RiskyKen/Armourers-Workshop/issues/100

**Closed by RiskyKen** 2017-08-22 08:35 UTC
Labels: investigating, need info
